server:
  port: 10000

spring:
  profiles:
    active: dev
  application:
    name: storage
  cloud:
    nacos:
      # 配置中心
      config:
        # 命名空间id(此处不用public,因public初始化的空间, id为空)
        namespace: 9e127940-3122-492e-bcfc-3fbd0bbd84c7
        # nacos的ip地址和端口 120.79.64.17:10848
        server-addr: 10.50.100.14:8848,10.50.100.15:8848,10.50.100.16:8848
        group: zhangdh
        # 这个就表示 在我们nacos命名空间id为 dev中 有一个data-id 为 demo-service.yml 的配置文件 读取这个里面的配置
        file-extension: yml
        config-retry-time: 300000
        # 共享配置, 可以把公共配置放在同个命名空间下，然后创建一个 common.yml 文件 ，里面可以放共用的配置

logging:
  file:
    path: ./log/${spring.application.name}
  config:  ./config/logback-spring.xml
  level:
    root: info
  logback:
    rollingpolicy:
      max-file-size: 500MB
      max-history: 30
      total-size-cap: 20GB

dubbo:
  application:
    name: dubbo-${spring.application.name}
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://${spring.cloud.nacos.config.server-addr}
    parameters:
      namespace: ${spring.cloud.nacos.config.namespace}