server:
  port: 10001

spring:
  profiles:
    active: dev
  application:
    name: order

logging:
  file:
    path: ./log/${spring.application.name}
  config:  ./config/logback-spring.xml
  level:
    root: info
  logback:
    rollingpolicy:
      max-file-size: 500MB
      max-history: 30
      total-size-cap: 20GB